### PR TITLE
Update aggregated symbols, remove duplicates

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/adviser/issues/1586

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by goern** [comment]
/approve

is this kind of an auto-pr by a cronjob to be auto-approved?

**Comment by fridex** [comment]
> is this kind of an auto-pr by a cronjob to be auto-approved?

It might be good idea to keep it manual now. Long-term having this automated is good idea - on a new major tensorflow release, recompute API symbols it exports and generate a PR like this one so that we have symbols up2date in the recommendation engine :+1:  A PR to thoth-adviser will also be needed. Do we want to derive an issue to be done?

**Comment by goern** [comment]
ja, I think creating an issue tbd later is a good idea

**Review by harshad16 — APPROVED** [review]

**Pull request merged**
